name: close-stale-issues-and-prs

permissions:
  pull-requests: write
  issues: write

defaults:
  run:
    shell: bash

on:
  workflow_call: { }

jobs:
  close:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    continue-on-error: true
    steps:
      - name: Close
        uses: actions/stale@v9
        with:
          # Issue
          exempt-issue-labels: "help wanted,good first issue,bug,bug-qa,enhancement"
          stale-issue-label: "stale"
          days-before-issue-stale: 30
          days-before-issue-close: 5
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          close-issue-message: "This issue was closed because it has been stalled for 5 days with no activity."
          # Pull Request
          exempt-pr-labels: "bug,bug-qa,enhancement"
          exempt-draft-pr: true
          days-before-pr-stale: 45
          days-before-pr-close: 10
          stale-pr-label: "stale"
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
          operations-per-run: 10000
