name: build-devops-images

permissions:
  contents: write
  pull-requests: read
  actions: write

defaults:
  run:
    shell: bash

on:
  workflow_dispatch: 
    inputs:
      target:
        description: 'Target'
        required: true
        type: string

jobs:
  cann:
    if: ${{ inputs.target == 'cann' }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        cann_chip:
          - '310p'
          - '910b'
        cann_version:
          - '8.0.RC2.alpha003'
        os_base:
          - 'ubuntu'
          - 'openeuler'
        os_version:
          - '20.04'
          - '20.03'
        py_version:
          - '3.9'
        exclude:
          - os_base: 'ubuntu'
            os_version: '20.03'
          - os_base: 'openeuler'
            os_version: '20.04'
    steps:
      - name: Maximize Docker Build Space
        uses: gpustack/.github/.github/actions/maximize-docker-build-space@main
        with:
          root-reserve-mb: 1024
          temp-reserve-mb: 1024
          swap-size-mb: 1024
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'cosdt/dockerfiles'
          ref: '99aaac257b3a98c059b0c055bc1c8d31e6c4fc99'
          fetch-depth: 1
          persist-credentials: false
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:qemu-v8.1.5
          platforms: "arm64"
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_DOCKERHUB_USERNAME }}
          password: ${{ secrets.CI_DOCKERHUB_PASSWORD }}
      - name: Package
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ github.workspace }}/cann/${{ matrix.os_base}}/Dockerfile
          context: ${{ github.workspace }}/cann
          platforms: 'linux/amd64,linux/arm64'
          build-args: |
            CANN_CHIP=${{ matrix.cann_chip }}
            CANN_VERSION=${{ matrix.cann_version }}
            BASE_VERSION=${{ matrix.os_version }}
            PY_VERSION=${{ matrix.py_version }}
          tags: 'gpustack/ascendai-cann:${{ matrix.cann_version }}-${{ matrix.cann_chip }}-${{ matrix.os_base}}${{ matrix.os_version }}-py${{ matrix.py_version }}'
          cache-from: |
            type=registry,ref=gpustack/build-cache:ascendai-cann-${{ matrix.cann_version }}-${{ matrix.cann_chip }}-${{ matrix.os_base}}${{ matrix.os_version }}-py${{ matrix.py_version }}
          cache-to: |
            type=registry,mode=max,oci-mediatypes=false,compression=gzip,ref=gpustack/build-cache:ascendai-cann-${{ matrix.cann_version }}-${{ matrix.cann_chip }}-${{ matrix.os_base}}${{ matrix.os_version }}-py${{ matrix.py_version }},ignore-error=true
          provenance: true
          sbom: true









